##################################################################################
# Configure cert-manager to use Lets Encrypt for external API gateway certificates
##################################################################################

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateway-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@authsamples-k8s.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53: {}
