#
# Configure Let's Encrypt to issue SSL certificates for the API gateway
#
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example-admin@example.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
