############################################################################
# Configure NGINX to receive TCP passthrough requests from the load balancer
############################################################################
controller:
  replicaCount: 1
  service:
    type: LoadBalancer
    enableHttp: false
