#
# These were initially spun up automatically by persistent volume claims and backed up from YAML
# I act as an administrator to provision these separately to application level deployments
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
    namespace: wordpress
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-045c99b7366359f9e
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: wp-pv-claim
    namespace: wordpress
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0fa6d01d5386aeb8a
  