#
# These were initially created automatically by persistent volume claims
# Act as an administrator to provision them separately to application level deployments
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
    namespace: wordpress
  hostPath:
    path: /tmp/hostpath-provisioner/mysql-data
    type: 'DirectoryOrCreate'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: wp-pv-claim
    namespace: wordpress
  hostPath:
    path: /tmp/hostpath-provisioner/wordpress-data
    type: 'DirectoryOrCreate'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
