kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: wordpress-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: wordpress.authsamples-k8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
  tls:
    - hosts:
        - wordpress.authsamples-k8s.com
      secretName: wordpress-ssl
